"""Agent-only Pydantic models for the sentiment analysis layer."""

from pydantic import BaseModel, ConfigDict, Field


class SentimentReportNarrative(BaseModel):
    """Narrative fields generated by the LLM layer."""

    model_config = ConfigDict(extra="forbid")

    summary: str = Field(
        description="Natural language summary of the sentiment posture."
    )
    reasoning: str = Field(
        description="Explanation for the summary and scoring decisions."
    )
    highlights: list[str] = Field(
        default_factory=list, description="Key drivers or notable content callouts."
    )
    recommendations: list[str] = Field(
        default_factory=list,
        description="Actionable monitoring or follow-up suggestions for downstream agents.",
    )
